//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUAN1_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public string id { get; set; }
        public string maBan { get; set; }
        public string maMon { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual BAN BAN { get; set; }
        public virtual MENU MENU { get; set; }
    }
}
