//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUAN1_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO
    {
        public string maNL { get; set; }
        public string tenNL { get; set; }
        public string soluong { get; set; }
        public string gia { get; set; }
        public string ngayNhap { get; set; }
        public string ngayHetHan { get; set; }
        public string ghichu { get; set; }
    }
}
