//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUAN1_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHLAM
    {
        public string id { get; set; }
        public string manv { get; set; }
        public string caLam { get; set; }
        public string ngayLam { get; set; }
        public string trangThai { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
